### ISSUE TITLE
Add chain logos

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-config-service#1021]
## Problem description

The design needs of our web app have evolved, and we want to display chain logos in the chain selector and in various other places in the app. See screenshot at the bottom.

Logos are currently hard-coded in the web app for each chain, so it would be great to have an uplodable field in Django to get them from the config service.

## Requirements
Please extend the chain config with the following fields:

* `chainLogo`
  – Must accept SVGs and PNGs w/o size limitations
  – Must be a required field

## Screenshot for reference
<img width="196" alt="Screenshot 2024-01-12 at 15 38 29" src="https://github.com/safe-global/safe-config-service/assets/381895/8f619016-5331-401d-8d15-f220d7a2d9a7">

**Comment by fmrsabino** [comment]
I've moved the `isTestnet` part to https://github.com/safe-global/safe-config-service/issues/1022. API proposal and requirements to be added.

**Comment by iamacook** [comment]
> For PNGs, file size is more important than dimensions.

There would be no file size limitation.

**Comment by iamacook** [comment]
> My point is, if you want to add any limitation, it should be on the file size, not the dimensions. Otherwise I don't have a preference.

[Pre-existing validation](https://github.com/safe-global/safe-config-service/blob/265d739f39f6857717f32a4d697a9326d43243b9/src/chains/models.py#L38) will be used for consistency, hence wanting to confirm. As you have no preference regarding this, I will continue with the current implementation.

**Comment by katspaugh** [comment]
As stated in the Requirements in the description, the upload field should accept SVG files which is not the case with the current production version.

**Comment by fmrsabino** [comment]
> As stated in the Requirements in the description, the upload field should accept SVG files which is not the case with the current production version.

The API in its current state needs to accommodate mobile platforms which have limited SVG support. SVG support can be considered in future iterations where we might need to provide not only PNGs but SVGs (both returned). This might mean either a new field or a filter on the resource to retrieve different file types.

Due to the scope of this change and since we have other fields which deal with PNG resources this won't be considered in the scope of "adding chain logos", but can of course be considered in the future once there's alignment on the support that we should provide for image resources.
