### ISSUE TITLE
Chain ids in Safe Apps

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-config-service#984]
## Problem
Atm we have to enter raw chain ids in Safe Apps entries.
This is very inconvienient and prone to error.

<img width="514" alt="Screenshot 2023-12-06 at 16 57 41" src="https://github.com/safe-global/safe-config-service/assets/381895/4890ae93-6cd3-49f4-9880-179fdbc2c33b">

## Request
It would be much better to use the Chain configs for this, like we do for Features.

<img width="772" alt="Screenshot 2023-12-06 at 16 58 28" src="https://github.com/safe-global/safe-config-service/assets/381895/7a30ddc0-c2ac-4985-96f7-90821b087dc1">

**Comment by fmrsabino** [comment]
I agree. One main reason why it was done initially like this was because the Safe Config Service has two "apps" (in the Django sense).

Safe Apps App is independent of the Chains App so you can run the config service with Safe Apps only (if that's what you'd need).

However this is then reflected on the lack of structured data on the Safe Apps Admin pages when it comes to Chains. I see two alternatives to improve this:

1. Add a Chains base app – simple app that only has the chain id and name. Then the full fledged Chains app would depend on the base one. The same for the Safe Apps App.
2. Make the Safe Apps App depend on the Chains App.

Option 1 is more robust, more modular, bigger refactor. 
Option 2 is less modular but simpler.

With the current state of the project I think it's important that we have some kind of structured data that can be shared (for Chains).

**Comment by katspaugh** [comment]
I would personally be OK even with just a duplicate Chains enum inside the Safe Apps. Just a chain id and name, so that we can easily enable/disable chains per app.
